*** Settings ***
Documentation     Variables for LU88 tests

*** Variables ***
# Application URLs
${GL_LU88_DOMAIN}                lu88.ch
${GL_LU88_URL}                   https://${GL_LU88_DOMAIN}/
${GL_LU88_GATEWAY_URL}           https://${GL_LU88_DOMAIN}/gw/api/v2/

# Test Data
#${VALID_USERNAME}            taynu001
#${VALID_USERNAME}           taylukm100    #tk co km 100
${VALID_USERNAME}            taydaily
${VALID_PASSWORD}            123456
