*** Settings ***
Documentation     Variables for Zo88 tests

*** Variables ***
# Application URLs
${GL_ZO88_DOMAIN}                zo88.ro
${GL_ZO88_URL}                   https://${GL_ZO88_DOMAIN}/
${GL_ZO88_GATEWAY_URL}           https://${GL_ZO88_DOMAIN}/gw/api/v2/

# Test Data
${VALID_USERNAME}            tayzo001
${VALID_PASSWORD}            123456


#${VALID_USERNAME}            atcfdaily
#${VALID_PASSWORD}            A@123456

#${VALID_USERNAME}            taynewzo    #tk km 100%
#${VALID_PASSWORD}            123456

